---
all:
  children:
    development:
      hosts:
        dev-server:
          ansible_host: host78.nird.club
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          
    production:
      hosts:
        prod-server:
          ansible_host: host74.nird.club
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  vars:
    ansible_python_interpreter: /usr/bin/python3
    project_name: countrypuff
    project_repo: https://github.com/pbertain/countrypuff.git
    python_version: "3.11"